@startuml
enum SpecialSymbolType {
    LeftRoundBracketToken,
    RightRoundBracketToken,
    PlusToken,
    MinusToken,
    MultToken,
    DivisionToken,
    GreaterToken,
    LessToken,
    GreaterOrEqualToken,
    LessOrEqualToken,
    EqualToken,
    NotEqualToken,
    SemicolonToken,
    ColonToken,
    AssignmentToken,
    LeftSquareBracketToken,
    RightSquareBracketToken,
    CommaToken,
    DotToken,
    DoubleDotToken,
    NilToken= 100,
    NotToken,
    AndToken,
    DivToken,
    PackedToken,
    ArrayToken,
    OfToken,
    FileToken,
    SetToken,
    RecordToken,
    EndToken,
    CaseToken,
    OrToken,
    FunctionToken,
    VarToken,
    ProcedureToken,
    BeginToken,
    IfToken,
    ThenToken,
    ElseToken,
    WhileToken,
    DoToken,
    RepeatToken,
    UntilToken,
    ForToken,
    ToToken,
    DowntoToken,
    WithToken,
    GotoToken,
    LabelToken,
    ConstToken,
    TypeToken,
    ProgramToken,
    ModToken,
    InToken= 134,
}
enum TriviaTokenType {
    EndOfFileToken,
    BadToken,
    UnknownSymbol,
}
@enduml
